### ISSUE TITLE
credential_pop typ

### ISSUE THREAD

**Issue by fmarino-ipzs** [peppelinux/draft-demarco-oauth-status-attestations#20]
The credential_pop is a JWT. I would consider `typ` as OPTIONAL and value it with `jwt`.
If omitted by default it is assumed to be `jwt`.

**Comment by OR13** [comment]
We might consider addressing the CWT case at the same time here.

Its against the JWT BCP to omit typ at this point: https://datatracker.ietf.org/doc/html/rfc8725#name-use-explicit-typing

I'd propose the following:

credential_pop MUST be a JWT or CWT.

The typ protected header parameter SHOULD be "kb+jwt" or "kb+cwt".

**Comment by peppelinux** [comment]
I and @fmarino-ipzs agreed with you, please open a PR if possibile

this issue is tagged under the milestone 01

**Comment by SaraConsoliACN** [comment]
This issue has been resolved by PR #37.
