### ISSUE TITLE
Need privacy considerations for issuer tracking

### ISSUE THREAD

**Issue by OR13** [peppelinux/draft-demarco-oauth-status-attestations#26]
Requiring continuous credential pop from a wallet so a status attestation is available also impacts holder privacy.

There should be privacy considerations that compare the trade offs associated this approach when compared to requesting status lists anonymously

**Comment by SaraConsoliACN** [comment]
@OR13 Can we consider this issue closed now that we have dedicated a chapter to privacy considerations?
