### ISSUE TITLE
Status Attestation in batch

### ISSUE THREAD

**Issue by fmarino-ipzs** [peppelinux/draft-demarco-oauth-status-attestations#30]
If the Wallet Instance has several Credentials issued by the same Issuer, we could introduce a mechanism to request all the Status attestations referring to the Credentials. Probably, this could be achieved by allowing the `credential_pop` to be an array.

**Comment by peppelinux** [comment]
Resolved by https://github.com/peppelinux/draft-demarco-oauth-status-attestations/pull/36
