### ISSUE TITLE
Change draft name

### ISSUE THREAD

**Issue by peppelinux** [peppelinux/draft-demarco-oauth-status-attestations#5]
> it would be good to avoid the term "attestations" because it is already used for a different purpose (in the IETF).

Could it be "status tokens" or "status assertions"?

**Comment by peppelinux** [comment]
What about Status Evidence?

This would be close to the Wallet Trust Evidence we have for eIDAS

**Comment by OR13** [comment]
I suggest we have a chat with RATS about this... they use these terms a lot, and will be very unhappy if we do not attempt to foster alignment... as will I : )

**Comment by peppelinux** [comment]
I suddenly realized that "status $something" misses the subject, the name would therefore be "Digital Credential Status Assertions"

This specification excludes its use with traditional OAuth 2.0/OIDC tokens. While the OAuth Status List shares some similarities, the OAuth 2.0 Introspection endpoint is deemed sufficient for such tokens due to several key differences:

    - **Interaction**: Parties interact differently in the context of traditional tokens compared to this specification.
    - **Privacy**: Distinct privacy requirements apply to each scenario.
    - **Offline usage**: Offline use cases, which necessitate this specification, are not a requirement for legacy infrastructures utilizing traditional tokens.

**Comment by peppelinux** [comment]
Following the Architecture for Trustworthy and Transparent Digital Supply Chains (SCITT), this looks pretty close to the purpose of this specs

````
{{NIST.SP.800-63-3}} defines "assertion" as "A statement from a verifier to an RP that contains information about a subscriber.
Assertions may also contain verified attributes."
````

@SaraConsoliACN could you please create a PR with the proposal of the specification name change?

**Comment by peppelinux** [comment]
Resolved by https://github.com/peppelinux/draft-demarco-oauth-status-attestations/pull/38
