### ISSUE TITLE
Align Terminology with OAuth

### ISSUE THREAD

**Issue by OR13** [peppelinux/draft-demarco-oauth-status-attestations#52]
Where possible, we should align terms, especially regarding "wallet and client".

Original comment :

https://github.com/peppelinux/draft-demarco-oauth-status-attestations/pull/51/files#r1606667394

**Comment by SaraConsoliACN** [comment]
The PR that aims to resolve, even if partially, this issue is: https://github.com/peppelinux/draft-demarco-oauth-status-attestations/pull/54

**Comment by peppelinux** [comment]
Resolved by https://github.com/peppelinux/draft-demarco-oauth-status-attestations/pull/51/files
